apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: sre-local
data:
  APP_NAME: "Auth Service"
  DEBUG: "true"
  DB_DIR: "/data"
  DB_NAME: "users.db"
  ROOT_PATH: "/auth"
  JWT_SECRET: "super-secret-dev"
  JWT_ALG: "HS256"
  JWT_EXPIRE_MINUTES: "60"


