apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting-service
  namespace: sre-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reporting-service
  template:
    metadata:
      labels:
        app: reporting-service
    spec:
      containers:
        - name: reporting-service
          image: reporting-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: ROOT_PATH
              value: "/reports"
            - name: DB_DIR
              value: "/data"
            - name: DB_NAME
              value: "expenses.db"
          volumeMounts:
            - name: expenses-db
              mountPath: /data
              readOnly: true
      volumes:
        - name: expenses-db
          persistentVolumeClaim:
            claimName: expenses-db-pvc
